project:
  type: website

website:
  title: "Dr Luke Kelly"
  search: false
  navbar: false
  google-analytics:
    tracking-id: UA-195863181-1
    storage: none

format:
  html:
    theme: [cerulean, styles.scss]
    page-layout: full
