project:
  type: website

website:
  title: "Dr Luke Kelly"
  search: false
  navbar: false
  google-analytics: G-9K2QC7MEPD
  site-url: 'https://lukejkelly.github.io'

format:
  html:
    theme: [cerulean, styles.scss]
    page-layout: full
